name: advent_of_code_2022
description: Playground for Advent of Code 2022 submissions. 

publish_to: none

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies: 
  characters: ^1.2.1
  collection: ^1.17.0

dev_dependencies:
  lints: ^2.0.1
  test: ^1.22.0
